#!/usr/bin/env python3
"""
Bootstrap new knowledge entries from external sources.

Sources:
  1. Documentation URLs (e.g., FastAPI docs, SQLAlchemy docs)
  2. GitHub README files
  3. Existing code files (extract patterns from real code)
  4. From a prompt (uses an LLM if available, otherwise produces a skeleton)

Usage:
  # From a documentation URL
  python scripts/entry_generator.py --from-url "https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/" --language python --category web

  # From a GitHub README
  python scripts/entry_generator.py --from-github "encode/httpx" --section "quickstart" --language python

  # From a local code file
  python scripts/entry_generator.py --from-code ./my_auth.py --language python --category web

  # From a prompt (uses an LLM if available, otherwise skeleton)
  python scripts/entry_generator.py --from-prompt "Redis pub/sub patterns in Python" --language python --category concurrency

  # Offline mode — always produce skeleton only
  python scripts/entry_generator.py --offline --from-prompt "Any topic" --language python

Output:
  - Generates a draft entry file following schema.md
  - Sets confidence: "draft" (needs human review)
  - Includes all required sections (some may be placeholder)
  - Saves to appropriate directory based on language/category
"""

import argparse
import html.parser
import json
import re
import sys
import urllib.request
import urllib.error
import ssl
from datetime import datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------

ENTRY_TEMPLATE = """---
id: "{entry_id}"
title: "{title}"
language: "{language}"
category: "{category}"
tags: [{tags}]
version: "{version}"
retrieval_hint: "{retrieval_hint}"
last_verified: "{today}"
confidence: "draft"
---

# {title}

{when_to_use}

## Standard Pattern

```{language_code}
{standard_pattern}
```

## Common Mistakes

```{language_code}
# WRONG: {wrong_desc}
{wrong_code}

# CORRECT: {correct_desc}
{correct_code}
```

## Gotchas
- This entry was auto-generated and needs human review
- Verify code examples are correct and idiomatic
- Add at least 3 WRONG/CORRECT pairs
- Add at least 3 Gotchas

## Related
- {related}

---

> **⚠️ DRAFT ENTRY — Needs Human Review**
> Generated by `scripts/entry_generator.py`. Please verify all patterns, add more examples,
> and change `confidence` to `high` or `medium` when ready.
"""

SKELETON_TEMPLATE = """---
id: "{entry_id}"
title: "{title}"
language: "{language}"
category: "{category}"
tags: [{tags}]
version: "{version}"
retrieval_hint: "{retrieval_hint}"
last_verified: "{today}"
confidence: "draft"
---

# {title}

## When to Use
- [TODO: Describe when to use this pattern]
- [TODO: Add 3-5 concrete scenarios]

## Standard Pattern

```{language_code}
# TODO: Add complete, runnable code example
# Include all imports, type hints, error handling
```

## Common Mistakes

```{language_code}
# WRONG: [TODO: Describe the mistake]
# TODO: Add bad code example

# CORRECT: [TODO: Describe the fix]
# TODO: Add good code example

# WRONG: [TODO: Another common mistake]
# TODO: Add bad example

# CORRECT: [TODO: The right way]
# TODO: Add good example

# WRONG: [TODO: Third common mistake]
# TODO: Add bad example

# CORRECT: [TODO: The right way]
# TODO: Add good example
```

## Gotchas
- [TODO: Add non-obvious pitfall]
- [TODO: Add edge case warning]
- [TODO: Add performance consideration]

## Related
- {related}

---

> **⚠️ DRAFT ENTRY — Needs Human Review**
> Generated by `scripts/entry_generator.py`. Please fill in all TODO sections,
> verify patterns, and change `confidence` to `high` or `medium` when ready.
"""

# ---------------------------------------------------------------------------
# Language defaults
# ---------------------------------------------------------------------------

LANGUAGE_DEFAULTS = {
    "python": {"version": "3.10+", "code_tag": "python", "related": "python/stdlib/pathlib.md"},
    "java": {"version": "17+", "code_tag": "java", "related": "java/stdlib/collections.md"},
    "typescript": {"version": "5.0+", "code_tag": "typescript", "related": "typescript/web/http-client.md"},
    "go": {"version": "1.21+", "code_tag": "go", "related": "go/stdlib/error-handling.md"},
    "rust": {"version": "1.70+", "code_tag": "rust", "related": "rust/stdlib/error-handling.md"},
    "csharp": {"version": "12.0+", "code_tag": "csharp", "related": "csharp/stdlib/collections.md"},
    "bash": {"version": "5.0+", "code_tag": "bash", "related": "bash/error-handling.md"},
    "sql": {"version": "ANSI", "code_tag": "sql", "related": "db/postgres/query-optimization.md"},
}


# ---------------------------------------------------------------------------
# Strategy 1: Generate from URL
# ---------------------------------------------------------------------------

class TextExtractor(html.parser.HTMLParser):
    """Extract readable text from HTML, preserving code blocks."""

    def __init__(self):
        super().__init__()
        self.text_parts: list[str] = []
        self.code_parts: list[str] = []
        self.in_code = False
        self.in_pre = False
        self.in_script = False
        self.in_style = False

    def handle_starttag(self, tag, attrs):
        if tag in ("script", "style"):
            self.in_script = True
        elif tag == "pre":
            self.in_pre = True
        elif tag == "code" and not self.in_pre:
            self.in_code = True

    def handle_endtag(self, tag):
        if tag in ("script", "style"):
            self.in_script = False
        elif tag == "pre":
            self.in_pre = False
        elif tag == "code":
            self.in_code = False

    def handle_data(self, data):
        if self.in_script or self.in_style:
            return
        stripped = data.strip()
        if not stripped:
            return
        if self.in_pre or self.in_code:
            self.code_parts.append(stripped)
        else:
            self.text_parts.append(stripped)


def fetch_url(url: str, timeout: int = 15) -> str | None:
    """Fetch a URL and return readable text."""
    try:
        ctx = ssl.create_default_context()
        req = urllib.request.Request(url, headers={"User-Agent": "llm-kb-generator/1.0"})
        with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:
            content_type = resp.headers.get("Content-Type", "")
            data = resp.read()

            if "text/html" in content_type:
                extractor = TextExtractor()
                extractor.feed(data.decode("utf-8", errors="replace"))
                # Combine text and code
                result = "\n".join(extractor.text_parts[:100])  # Limit text
                if extractor.code_parts:
                    result += "\n\n## Code Snippets\n```\n"
                    result += "\n".join(extractor.code_parts[:20])
                    result += "\n```"
                return result
            else:
                return data.decode("utf-8", errors="replace")
    except Exception as e:
        return f"# Error fetching URL\n\nCould not fetch {url}: {e}\n\nPlease add content manually."


def generate_from_url(
    url: str,
    language: str,
    category: str,
    offline: bool = False,
) -> str:
    """Generate a draft entry from a documentation URL."""
    ld = LANGUAGE_DEFAULTS.get(language, LANGUAGE_DEFAULTS["python"])

    # Derive title and slug from URL
    url_parts = url.rstrip("/").split("/")
    slug = url_parts[-1] if url_parts else "topic"
    title_words = slug.replace("-", " ").replace("_", " ").title()
    title = f"{title_words} in {language.title()}"

    if offline:
        content = SKELETON_TEMPLATE.format(
            entry_id=f"{language}-{category}-{slug}",
            title=title,
            language=language,
            category=category,
            tags=f'"{slug}", "{language}", "{category}"',
            version=ld["version"],
            retrieval_hint=f"{slug} {language} {category} how to use pattern",
            today=datetime.now().strftime("%Y-%m-%d"),
            language_code=ld["code_tag"],
            related=ld["related"],
        )
        return content

    # Fetch URL content
    fetched = fetch_url(url)

    # Extract code snippets from fetched content
    code_blocks = re.findall(r"```.*?\n(.*?)```", fetched or "", re.DOTALL)
    standard_pattern = "\n".join(code_blocks[:3]) if code_blocks else "# TODO: Add from documentation"

    # Try to extract first paragraphs for "When to Use"
    paragraphs = [p.strip() for p in (fetched or "").split("\n") if len(p.strip()) > 50]
    when_to_use = "## When to Use\n"
    for p in paragraphs[:5]:
        if p and not p.startswith("#") and not p.startswith("```"):
            when_to_use += f"- {p[:200]}\n"

    if not paragraphs:
        when_to_use += "- [TODO: Extract from documentation]\n"

    content = ENTRY_TEMPLATE.format(
        entry_id=f"{language}-{category}-{slug}",
        title=title,
        language=language,
        category=category,
        tags=f'"{slug}", "{language}", "{category}"',
        version=ld["version"],
        retrieval_hint=f"{slug} {language} {category} how to use pattern",
        today=datetime.now().strftime("%Y-%m-%d"),
        language_code=ld["code_tag"],
        when_to_use=when_to_use,
        standard_pattern=standard_pattern,
        wrong_desc="TODO: Describe a common mistake",
        wrong_code="# TODO: Add bad code example",
        correct_desc="The right way",
        correct_code="# TODO: Add good code example",
        related=ld["related"],
    )

    return content


# ---------------------------------------------------------------------------
# Strategy 2: Generate from GitHub README
# ---------------------------------------------------------------------------

def _fetch_github_readme(repo: str, section: str | None = None, timeout: int = 15) -> str | None:
    """Fetch a GitHub repository's README via raw.githubusercontent.com."""
    try:
        ctx = ssl.create_default_context()
        # Try main branch first, then master
        for branch in ("main", "master"):
            url = f"https://raw.githubusercontent.com/{repo}/{branch}/README.md"
            try:
                req = urllib.request.Request(url, headers={"User-Agent": "llm-kb-generator/1.0"})
                with urllib.request.urlopen(req, timeout=timeout, context=ctx) as resp:
                    content = resp.read().decode("utf-8", errors="replace")
                    if section:
                        # Try to find the section
                        section_match = re.search(
                            rf"#+\s+{re.escape(section)}.*?\n(.*?)(?=\n#+\s|\Z)",
                            content, re.DOTALL | re.IGNORECASE
                        )
                        if section_match:
                            return section_match.group(1).strip()
                    return content
            except Exception:
                continue
        return None
    except Exception:
        return None


def generate_from_github(
    repo: str,
    section: str | None,
    language: str,
    category: str | None = None,
    offline: bool = False,
) -> str:
    """Generate a draft entry from a GitHub repository README."""
    ld = LANGUAGE_DEFAULTS.get(language, LANGUAGE_DEFAULTS["python"])

    # Derive title from repo name
    repo_name = repo.split("/")[-1]
    title = f"{repo_name.title()} - {section or 'Overview'}"

    if not category:
        category = "stdlib"

    slug = repo_name.lower()

    if offline:
        return SKELETON_TEMPLATE.format(
            entry_id=f"{language}-{category}-{slug}",
            title=title,
            language=language,
            category=category,
            tags=f'"{slug}", "{language}", "{category}", "{repo_name}"',
            version=ld["version"],
            retrieval_hint=f"{repo_name} {slug} {language} {section or ''} how to use",
            today=datetime.now().strftime("%Y-%m-%d"),
            language_code=ld["code_tag"],
            related=ld["related"],
        )

    readme_content = _fetch_github_readme(repo, section)

    if readme_content:
        # Extract code blocks
        code_blocks = re.findall(r"```.*?\n(.*?)```", readme_content, re.DOTALL)
        standard_pattern = "\n".join(code_blocks[:3]) if code_blocks else "# TODO: Add from README"

        # Extract paragraphs for "When to Use"
        paragraphs = [p.strip() for p in readme_content.split("\n") if len(p.strip()) > 50]
        when_to_use = "## When to Use\n"
        for p in paragraphs[:5]:
            if p and not p.startswith("#") and not p.startswith("```") and not p.startswith("!"):
                when_to_use += f"- {p[:200]}\n"
    else:
        standard_pattern = "# TODO: Add from GitHub README"
        when_to_use = "## When to Use\n- [TODO: Extract from README]\n"

    return ENTRY_TEMPLATE.format(
        entry_id=f"{language}-{category}-{slug}",
        title=title,
        language=language,
        category=category,
        tags=f'"{slug}", "{language}", "{category}", "{repo_name}"',
        version=ld["version"],
        retrieval_hint=f"{repo_name} {slug} {language} {section or ''} how to use",
        today=datetime.now().strftime("%Y-%m-%d"),
        language_code=ld["code_tag"],
        when_to_use=when_to_use,
        standard_pattern=standard_pattern[:3000],  # Truncate long READMEs
        wrong_desc="TODO: Describe a common mistake",
        wrong_code="# TODO: Add bad code example",
        correct_desc="The right way",
        correct_code="# TODO: Add good code example",
        related=ld["related"],
    )


# ---------------------------------------------------------------------------
# Strategy 3: Generate from code file
# ---------------------------------------------------------------------------

def generate_from_code(
    filepath: str,
    language: str,
    category: str,
) -> str:
    """Generate a draft entry by analyzing a local code file."""
    ld = LANGUAGE_DEFAULTS.get(language, LANGUAGE_DEFAULTS["python"])
    path = Path(filepath)

    if not path.exists():
        print(f"Error: File not found: {filepath}", file=sys.stderr)
        sys.exit(1)

    source = path.read_text(encoding="utf-8", errors="replace")
    slug = path.stem.lower()
    title = f"{path.stem.replace('_', ' ').replace('-', ' ').title()} Pattern"

    # Extract function and class names
    funcs = re.findall(r"^(?:async\s+)?def\s+(\w+)", source, re.MULTILINE)
    classes = re.findall(r"^class\s+(\w+)", source, re.MULTILINE)
    imports = re.findall(r"^(?:from\s+\S+\s+)?import\s+(.+)", source, re.MULTILINE)

    tags = [slug, language, category]
    for f in funcs[:3]:
        tags.append(f.lower())
    for c in classes[:2]:
        tags.append(c.lower())

    when_to_use = "## When to Use\n"
    if funcs:
        when_to_use += f"- When you need to implement `{', '.join(funcs[:3])}` functionality\n"
    if classes:
        when_to_use += f"- When working with `{', '.join(classes[:3])}` class patterns\n"
    if not funcs and not classes:
        when_to_use += "- [TODO: Describe when to use this pattern]\n"

    standard_pattern = source[:3000]  # First 3000 chars
    if len(source) > 3000:
        standard_pattern += "\n\n# ... (truncated for draft)"

    return ENTRY_TEMPLATE.format(
        entry_id=f"{language}-{category}-{slug}",
        title=title,
        language=language,
        category=category,
        tags=", ".join(f'"{t}"' for t in tags[:8]),
        version=ld["version"],
        retrieval_hint=f"{slug} {language} {category} {' '.join(funcs[:3])} {' '.join(classes[:2])}",
        today=datetime.now().strftime("%Y-%m-%d"),
        language_code=ld["code_tag"],
        when_to_use=when_to_use,
        standard_pattern=standard_pattern,
        wrong_desc="TODO: Describe a common mistake",
        wrong_code="# TODO: Add bad code example",
        correct_desc="The right way",
        correct_code="# TODO: Add good code example",
        related=ld["related"],
    )


# ---------------------------------------------------------------------------
# Strategy 4: Generate from prompt (skeleton or LLM-assisted)
# ---------------------------------------------------------------------------

def generate_from_prompt(
    prompt: str,
    language: str,
    category: str | None = None,
    offline: bool = False,
    llm_url: str | None = None,
    llm_model: str | None = None,
) -> str:
    """Generate a draft entry from a prompt. Uses LLM if available."""
    ld = LANGUAGE_DEFAULTS.get(language, LANGUAGE_DEFAULTS["python"])

    if not category:
        category = "stdlib"

    # Create a URL-safe slug from the prompt
    slug = re.sub(r"[^a-z0-9]+", "-", prompt.lower().strip())[:50].strip("-")
    title = prompt.strip()[:100]

    if offline or not llm_url:
        # Produce skeleton
        return SKELETON_TEMPLATE.format(
            entry_id=f"{language}-{category}-{slug}",
            title=title,
            language=language,
            category=category,
            tags=f'"{slug}", "{language}", "{category}"',
            version=ld["version"],
            retrieval_hint=f"{slug} {language} {category} how to use",
            today=datetime.now().strftime("%Y-%m-%d"),
            language_code=ld["code_tag"],
            related=ld["related"],
        )

    # Try LLM-assisted generation
    try:
        llm_prompt = f"""Generate a knowledge base entry for an LLM code reference system.

Topic: {prompt}
Language: {language}
Category: {category}

The entry should be a Markdown file with YAML frontmatter following this exact schema:

---
id: "{language}-{category}-{slug}"
title: "{title}"
language: "{language}"
category: "{category}"
tags: ["tag1", "tag2", "tag3"]
version: "{ld['version']}"
retrieval_hint: "keywords for search"
last_verified: "{datetime.now().strftime('%Y-%m-%d')}"
confidence: "draft"
---

# Title

## When to Use
- Concrete scenario 1
- Concrete scenario 2

## Standard Pattern
(complete runnable code with imports, type hints, error handling)

## Common Mistakes
# WRONG: description
(bad code)
# CORRECT: description
(good code)
(Include at least 3 WRONG/CORRECT pairs)

## Gotchas
- Pitfall 1
- Pitfall 2
- Pitfall 3

## Related
- related-entry.md

Include at the end:
> **⚠️ DRAFT ENTRY — Needs Human Review**

Return ONLY the markdown content, nothing else."""

        ctx = ssl.create_default_context()
        data = json.dumps({
            "model": llm_model or "local-model",
            "messages": [
                {"role": "system", "content": "You are a technical writer creating code pattern reference entries."},
                {"role": "user", "content": llm_prompt},
            ],
            "temperature": 0.3,
            "max_tokens": 4096,
        }).encode()

        req = urllib.request.Request(
            llm_url,
            data=data,
            headers={"Content-Type": "application/json"},
        )
        with urllib.request.urlopen(req, timeout=120, context=ctx) as resp:
            result = json.loads(resp.read().decode())
            content = result["choices"][0]["message"]["content"]

        # Ensure frontmatter is present
        if not content.startswith("---"):
            content = f"---\nid: \"{language}-{category}-{slug}\"\ntitle: \"{title}\"\nlanguage: \"{language}\"\ncategory: \"{category}\"\ntags: [\"{slug}\", \"{language}\", \"{category}\"]\nversion: \"{ld['version']}\"\nretrieval_hint: \"{slug} {language}\"\nlast_verified: \"{datetime.now().strftime('%Y-%m-%d')}\"\nconfidence: \"draft\"\n---\n\n{content}"

        return content

    except Exception as e:
        print(f"LLM generation failed ({e}), falling back to skeleton.", file=sys.stderr)
        return SKELETON_TEMPLATE.format(
            entry_id=f"{language}-{category}-{slug}",
            title=title,
            language=language,
            category=category,
            tags=f'"{slug}", "{language}", "{category}"',
            version=ld["version"],
            retrieval_hint=f"{slug} {language} {category} how to use",
            today=datetime.now().strftime("%Y-%m-%d"),
            language_code=ld["code_tag"],
            related=ld["related"],
        )


# ---------------------------------------------------------------------------
# Output and validation
# ---------------------------------------------------------------------------

def determine_output_path(
    language: str,
    category: str,
    slug: str,
    kb_path: Path,
) -> Path:
    """Determine the output path for a generated entry."""
    # Map languages to their standard directory names
    lang_dirs = {
        "python": "python",
        "java": "java",
        "typescript": "typescript",
        "go": "go",
        "rust": "rust",
        "csharp": "csharp",
        "bash": "bash",
        "sql": "db",
        "yaml": "devops",
    }

    lang_dir = lang_dirs.get(language, language)
    base = kb_path / lang_dir / category
    base.mkdir(parents=True, exist_ok=True)

    filename = f"{slug}.md"
    return base / filename


def save_entry(content: str, output_path: Path, dry_run: bool = False) -> Path:
    """Save the generated entry to disk."""
    if dry_run:
        print(f"[DRY RUN] Would save to: {output_path}")
        return output_path

    output_path.write_text(content, encoding="utf-8")
    print(f"✅ Saved draft entry to: {output_path}")
    return output_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Bootstrap new knowledge base entries from external sources",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/entry_generator.py --from-url "https://fastapi.tiangolo.com/tutorial/security/oauth2-jwt/" --language python --category web
  python scripts/entry_generator.py --from-github "encode/httpx" --section "quickstart" --language python
  python scripts/entry_generator.py --from-code ./my_auth.py --language python --category web
  python scripts/entry_generator.py --from-prompt "Redis pub/sub patterns in Python" --language python
  python scripts/entry_generator.py --offline --from-prompt "Any topic" --language python
        """,
    )

    # Source selection (mutually exclusive)
    source_group = parser.add_mutually_exclusive_group(required=True)
    source_group.add_argument("--from-url", type=str, help="URL to fetch documentation from")
    source_group.add_argument("--from-github", type=str, help="GitHub repo (e.g., 'encode/httpx')")
    source_group.add_argument("--from-code", type=str, help="Path to local code file to analyze")
    source_group.add_argument("--from-prompt", type=str, help="Topic prompt to generate from")

    # Options
    parser.add_argument("--language", type=str, required=True,
                        help="Primary language (python, java, typescript, go, rust, csharp, bash)")
    parser.add_argument("--category", type=str, default=None,
                        help="Category (stdlib, web, db, testing, data, patterns, crypto, devops, concurrency)")
    parser.add_argument("--section", type=str, default=None,
                        help="Specific section to extract from GitHub README")
    parser.add_argument("--offline", action="store_true",
                        help="Produce skeleton only (no network calls)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be generated without saving")
    parser.add_argument("--kb-path", type=str, default=".",
                        help="Path to knowledge base root")
    parser.add_argument("--llm-url", type=str, default=None,
                        help="OpenAI-compatible API URL for LLM-assisted generation")
    parser.add_argument("--llm-model", type=str, default=None,
                        help="Model name for LLM-assisted generation")

    args = parser.parse_args()

    if args.language not in LANGUAGE_DEFAULTS:
        print(f"Warning: Language '{args.language}' not in known defaults. Using generic defaults.",
              file=sys.stderr)

    kb_path = Path(args.kb_path)

    # Generate based on source
    if args.from_url:
        if args.offline:
            print("Offline mode: producing skeleton from URL")
        content = generate_from_url(
            args.from_url, args.language, args.category or "stdlib",
            offline=args.offline,
        )
        slug = args.from_url.rstrip("/").split("/")[-1]
    elif args.from_github:
        if args.offline:
            print("Offline mode: producing skeleton from GitHub repo")
        content = generate_from_github(
            args.from_github, args.section, args.language,
            category=args.category, offline=args.offline,
        )
        slug = args.from_github.split("/")[-1].lower()
    elif args.from_code:
        content = generate_from_code(
            args.from_code, args.language, args.category or "stdlib",
        )
        slug = Path(args.from_code).stem.lower()
    elif args.from_prompt:
        content = generate_from_prompt(
            args.from_prompt, args.language, args.category,
            offline=args.offline, llm_url=args.llm_url, llm_model=args.llm_model,
        )
        slug = re.sub(r"[^a-z0-9]+", "-", args.from_prompt.lower().strip())[:50].strip("-")
    else:
        parser.error("No source specified")

    # Determine output path
    output_path = determine_output_path(
        args.language, args.category or "stdlib", slug, kb_path,
    )

    # Save
    save_entry(content, output_path, dry_run=args.dry_run)

    if not args.dry_run:
        # Try to validate the generated entry
        print("\nValidating generated entry...")
        try:
            sys.path.insert(0, str(Path(__file__).parent.parent))
            from validate_kb import validate_entry
            errors = validate_entry(output_path)
            if errors:
                print(f"⚠️  Validation found {len(errors)} issue(s):")
                for err in errors:
                    print(f"   - {err}")
                print("\nThis is expected for draft entries. Fix issues before marking as high confidence.")
            else:
                print("✅ Entry passes schema validation!")
        except Exception as e:
            print(f"⚠️  Could not validate: {e}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
